### PR TITLE
Cleanup connection pool configuration

### PR DESCRIPTION
**Pull request by amottier**
Remove usage of c3p0 connection pool properties. As configuration use Tomcat JDBC Pool property (validationInterval) force the appropriate connection pool factory (org.apache.tomcat.jdbc.pool.DataSourceFactory).

### CODE REVIEW

**Comment by educhastenier** [comment]
What is the expected gain of this change?

**Comment by amottier** [comment]
Expected changes is first to have coherency between the connection pool implementation (DBCP, Tomcat JDBC Pool, c3p0) used and properties defined in configuration file.

Another benefit would be to have coherent behavior for various Tomcat setup. Default implementation of connection pool depends on Tomcat distribution (standard distribution use DBCP, Debian/Ubuntu use Tomcat JDBC Pool) so it is not a good idea to rely on default configuration.

Last we might get some performance improvement according to information available in [Tomcat documentation](http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Introduction)

**Comment by baptistemesta** [comment]
It seems that it produce an issue:
In a studio environnement if you kill the studio, the tomcat in then killed by the studio watchdog and in that case the tomcat never shutdown.
It seems that the database is closed before the engine is shutdown and that make quartz to be locked on shutdown. Please come see me for more details on that, i revert this PR.

**Comment by amottier** [comment]
Disabling h2 shutdown hook seems to avoid the issue.

To disable shutdown hook set DB_CLOSE_ON_EXIT value to false for the 4 connections configured in `conf/Catalina/localhost/bonita.xml` and in `conf/bitronix-resources.properties`

Issue is probably due to the fact that Tomcat shutdown hook (see [CatalinaShutdownHook](http://svn.apache.org/repos/asf/tomcat/tc7.0.x/tags/TOMCAT_7_0_55/java/org/apache/catalina/startup/Catalina.java) inner class) is slower than h2 shutdown hook (see [Database](https://github.com/h2database/h2database/blob/278e6e8172db9ff393afec415cebe5fbb719ce65/h2/src/main/org/h2/engine/Database.java#L273) and [DatabaseCloser](https://github.com/h2database/h2database/blob/278e6e8172db9ff393afec415cebe5fbb719ce65/h2/src/main/org/h2/engine/DatabaseCloser.java) ). So h2 database is closed before the Quartz is shutdown (Quartz shutdown is triggered by the EngineInitializerListener).

In a graceful shutdown situation, h2 hook is probably never called because h2 database is probably closed by the h2 listener.

**Pull request merged**
