### PR TITLE
in Tomcat and Jboss, set property 'org.bonitasoft.engine.incident.folder'

### PR DESCRIPTION
**Pull request by educhastenier**
...to put file in default log/ folder (according to bundle type)

### CODE REVIEW

**Comment by laurentleseigneur** [comment]
linked with https://github.com/bonitasoft/bonita-engine-sp/pull/207

**Comment by laurentleseigneur** [comment]
missing .bat update

**Comment by educhastenier** [comment]
.bat files done (tomcat + jboss)

**Comment by laurentleseigneur** [comment]
LGTM

**Pull request merged**
